wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.7
    t:
      1:
      - 1
      - 5
      4: 3.7.7
      5: 0.10.30
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 32
epoch:
  desc: null
  value: 60
lr_config:
  desc: null
  value:
    min_lr_ratio: 2.0e-06
    periods:
    - 20
    - 12
    - 12
    - 12
    - 12
    restart_weights:
    - 1
    - 0.7
    - 0.6
    - 0.5
    - 0.4
    type: CosineRestartLrUpdaterHook
    warmup: linear
    warmup_iters: 200
    warmup_ratio: 0.1
optimizer:
  desc: null
  value:
    lr: 0.0001
    type: AdamW
    weight_decay: 0.0001
optimizer_config:
  desc: null
  value:
    grad_clip:
      max_norm: 35
      norm_type: 2
    type: OptimizerHook
